# Generated by Django 4.2.24 on 2025-09-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.JSONField()),
                ("prediction", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
